###
POST http://localhost:3002/ship HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvc2EubWVsdHJvc28xQGV4YW1wbGUuY29tIiwiaWF0IjoxNjY5ODE1NjU2LCJleHAiOjE2Njk4MjI4NTZ9.uzdR1BJDwz6v2NEHWReyfZNEGZT2uVNfBrOXkuJrYow

{
    "name": "xa",
    "gas": "protocultur"
}

###
GET http://localhost:3002/ship HTTP/1.1